#ifndef PrjFSCommon_h
#define PrjFSCommon_h

#include <stdint.h>
#include <stdbool.h>

#define PrjFSMaxPath            1024
#define PrjFSKextBundleId       "io.gvfs.PrjFSKext"
#define PrjFSKernelControlName  "io.gvfs.PrjFSKext.ctl"

#define PrjFSServiceClass       "io_gvfs_PrjFS"

// TODO: move this to an autogenerated header.
#define PrjFSKextVersion "0.1"
// Name of property on the main PrjFS IOService indicating the kext version, to be checked by user space
#define PrjFSKextVersionKey "io.gvfs.PrjFSKext.Version"

typedef enum
{
    FileFlags_Invalid = 0,
    
    FileFlags_IsInVirtualizationRoot    = 0x00000008, // UF_OPAQUE
    FileFlags_IsEmpty                   = 0x00000010, // UF_NOUNLINK
    
} FileFlags;

// User client types to be passed to IOServiceOpen.
enum PrjFSServiceUserClientType
{
    UserClientType_Invalid = 0,
    
    UserClientType_Provider,
    UserClientType_Log,
};

#endif /* PrjFSCommon_h */
