#ifndef PrjFSCommon_h
#define PrjFSCommon_h

#include <stdint.h>
#include <stdbool.h>

#define PrjFSMaxPath            1024
#define PrjFSKextBundleId       "io.gvfs.PrjFSKext"

#define PrjFSServiceClass       "io_gvfs_PrjFS"

// TODO: move this to an autogenerated header.
#define PrjFSKextVersion "0.1"
// Name of property on the main PrjFS IOService indicating the kext version, to be checked by user space
#define PrjFSKextVersionKey "io.gvfs.PrjFSKext.Version"

#define PrjFSProviderPathKey "io.gvfs.PrjFSKext.ProviderUserClient.Path"

typedef enum
{
    FileFlags_Invalid = 0,
    
    FileFlags_IsInVirtualizationRoot    = 0x00000008, // UF_OPAQUE
    FileFlags_IsEmpty                   = 0x00000010, // UF_NOUNLINK
    
} FileFlags;

// User client types to be passed to IOServiceOpen.
enum PrjFSServiceUserClientType
{
    UserClientType_Invalid = 0,
    
    UserClientType_Provider,
    UserClientType_Log,
};

// When building the kext in user space for unit testing, we want some functions
// to have external linkage in order to make them testable
#ifdef KEXT_UNIT_TESTING
#define KEXT_TESTABLE_STATIC
#define KEXT_TESTABLE_STATIC_INLINE
#else
#define KEXT_TESTABLE_STATIC static
#define KEXT_TESTABLE_STATIC_INLINE static inline
#endif

#endif /* PrjFSCommon_h */
