#!/bin/bash
if [ -f /Library/LaunchDaemons/org.vfsforgit.prjfs.PrjFSKextLogDaemon.plist ]; then
    unloadCmd="sudo launchctl unload -w /Library/LaunchDaemons/org.vfsforgit.prjfs.PrjFSKextLogDaemon.plist"
    echo "Unloading PrjFSKextLogDaemon: '$unloadCmd'..."
    eval $unloadCmd || exit 1
fi

KEXTBUNDLEID="org.vfsforgit.PrjFSKext"
isKextLoadedCmd="/usr/sbin/kextstat -l -b $KEXTBUNDLEID | wc -l"
isKextLoaded=$(eval $isKextLoadedCmd)
if [ "$isKextLoaded" -gt 0 ]; then
	unloadCmd="/sbin/kextunload -b $KEXTBUNDLEID"
    echo $unloadCmd
    eval $unloadCmd || exit 1
fi

LEGACYKEXTBUNDLEID="io.gvfs.PrjFSKext"
isKextLoadedCmd="/usr/sbin/kextstat -l -b $LEGACYKEXTBUNDLEID | wc -l"
isKextLoaded=$(eval $isKextLoadedCmd)
if [ "$isKextLoaded" -gt 0 ]; then
	unloadCmd="/sbin/kextunload -b $LEGACYKEXTBUNDLEID"
    echo $unloadCmd
    eval $unloadCmd || exit 1
fi