#!/bin/bash

KEXTBUNDLEID="org.vfsforgit.PrjFSKext"
isKextLoadedCmd="/usr/sbin/kextstat -l -b $KEXTBUNDLEID | wc -l"
isKextLoaded=$(eval $isKextLoadedCmd)
if [ "$isKextLoaded" -gt 0 ]; then
    unloadCmd="/sbin/kextunload -b $KEXTBUNDLEID"
    echo $unloadCmd
    eval $unloadCmd || exit 1
fi

LEGACYKEXTBUNDLEID="io.gvfs.PrjFSKext"
isKextLoadedCmd="/usr/sbin/kextstat -l -b $LEGACYKEXTBUNDLEID | wc -l"
isKextLoaded=$(eval $isKextLoadedCmd)
if [ "$isKextLoaded" -gt 0 ]; then
    unloadCmd="/sbin/kextunload -b $LEGACYKEXTBUNDLEID"
    echo $unloadCmd
    eval $unloadCmd || exit 1
fi
