VERSION=$1
if [ -z $VERSION ]; then
  VERSION="0.2.173.2"
fi

# Generate PrjFSVersion.h
SCRIPTDIR=$(dirname ${BASH_SOURCE[0]})
cat >$SCRIPTDIR/../../../BuildOutput/PrjFSVersion.h <<TEMPLATE
// This header file was generated by GeneratePrjFSVersionHeader.sh

#define PrjFSVersionString "$VERSION"
TEMPLATE
