VERSION=$1
if [ -z $VERSION ]; then
  VERSION="0.2.173.2"
fi

# Generate PrjFSVersion.h
SCRIPTDIR=$(dirname ${BASH_SOURCE[0]})
VERSIONHEADER=$SCRIPTDIR/../../../BuildOutput/PrjFSVersion.h

echo "Generating $VERSIONHEADER with version $VERSION"

cat >$VERSIONHEADER <<TEMPLATE
// This header file was generated by GeneratePrjFSVersionHeader.sh

#define PrjFSVersionString "$VERSION"
TEMPLATE
