@IF "%_echo%"=="" (ECHO OFF) ELSE (ECHO ON)

REM Set environment variables for interesting paths that scripts might need access to.
PUSHD %~dp0
SET VFS_SCRIPTSDIR=%CD%
POPD

CALL :RESOLVEPATH "%VFS_SCRIPTSDIR%\.."
SET VFS_SRCDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_SRCDIR%\.."
SET VFS_ENLISTMENTDIR=%_PARSED_PATH_%

SET VFS_OUTDIR=%VFS_ENLISTMENTDIR%\out
SET VFS_PACKAGESDIR=%VFS_ENLISTMENTDIR%\packages
SET VFS_PUBLISHDIR=%VFS_ENLISTMENTDIR%\publish

REM Clean up
SET _PARSED_PATH_=

GOTO :EOF

:RESOLVEPATH
SET "_PARSED_PATH_=%~f1"
GOTO :EOF
