@ECHO OFF

REM Set environment variables for interesting paths that scripts might need access to.
PUSHD %~dp0
SET VFS_SRCDIR=%CD%

CALL :RESOLVEPATH "%VFS_SRCDIR%\Scripts"
SET VFS_SCRIPTSDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_SRCDIR%\.."
SET VFS_ENLISTMENTDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_ENLISTMENTDIR%\BuildOutput"
SET VFS_OUTPUTDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_ENLISTMENTDIR%\packages"
SET VFS_PACKAGESDIR=%_PARSED_PATH_%

CALL :RESOLVEPATH "%VFS_ENLISTMENTDIR%\.tools"
SET VFS_TOOLSDIR=%_PARSED_PATH_%

REM Clean up
SET _PARSED_PATH_=

GOTO :EOF

:RESOLVEPATH
SET "_PARSED_PATH_=%~f1"
GOTO :EOF
