name: $(date:yy)$(DayOfYear)$(rev:.r)
trigger: none
pr: none

variables:
  GVFSMajorAndMinorVersion: 2.0
  GVFSRevision: $(Build.BuildNumber)
  BuildConfiguration: Release
  TeamName: GVFS

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

  - repository: VFSForGit
    type: github
    name: microsoft/VFSForGit
    ref: releases/shipped
    endpoint: GitHub-VFSForGit

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES

    featureFlags:
      incrementalSDLBinaryAnalysis: false
      disableNetworkIsolation: true

    sdl:
      binskim:
        enabled: false
        justificationForDisabling: "Guardian and BinSkim do not support a suppression for InnoSetup installer file"
      sourceRepositoriesToScan:
        include:
        - repository: VFSForGit

    stages:
      - stage: Release

        jobs:
        - job: Build
          templateContext:
            mb:
              signing:
                enabled: true
                feedSource: 'https://pkgs.dev.azure.com/mseng/_packaging/MicroBuildToolset/nuget/v3/index.json'
                signType: real
                signWithProd: true

            outputs:
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)\GVFS.Installers
                artifactName: Installer
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)\FastFetch
                artifactName: FastFetch
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)\Symbols
                artifactName: Symbols
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)\GVFS.FunctionalTests
                artifactName: FunctionalTests

          steps:
            - checkout: VFSForGit
              displayName: 'Checkout VFS for Git'
              path: vfsforgit\src

            - task: NuGetToolInstaller@1
              displayName: 'Use NuGet 6.x'
              inputs:
                versionSpec: '6.x'

            - script: |
                $(Agent.BuildDirectory)\vfsforgit\src\scripts\Build.bat ^
                  $(BuildConfiguration) ^
                  $(GVFSMajorAndMinorVersion).$(GVFSRevision) ^
                  detailed
              displayName: 'Build and sign ($(BuildConfiguration))'

            - script: |
                $(Agent.BuildDirectory)\vfsforgit\src\scripts\RunUnitTests.bat ^
                  $(BuildConfiguration)
              displayName: 'Run unit tests'

            - script: |
                $(Agent.BuildDirectory)\vfsforgit\src\scripts\CreateBuildArtifacts.bat ^
                  $(BuildConfiguration) ^
                  $(Build.ArtifactStagingDirectory)
              displayName: 'Create artifacts'
